name: dasilva-invariants
channels:
 - conda-forge
dependencies:
 - python=3
 - numpy
 - scipy
 - astropy
 - mypy
 - pandas
 - pyhdf
 - pip
 - pip:
   - ai.cs
   - flake8
   - spacepy
   - types-python-dateutil
