name: dasilva-invariants
channels:
 - conda-forge
dependencies:
 - python==3.11
 - numpy>=1.26.3 
 - astropy>=5.1
 - cmake>=3.28.1
 - h5py>=3.10.0
 - pandas>=1.5.2
 - pytest   
 - pyvista
 - scipy>=1.9.3
 - scikit-build>=0.17.6
 - pip
 - pip:
    - ai.cs
    - cdflib
    - flake8
    - mypy
    - PyGeopack>=1.2.4
    - pyhdf
    - types-python-dateutil

