name: dasilva-invariants
channels:
 - conda-forge
dependencies:
 - python=3
 - cxx-compiler
 - numpy
 - scipy
 - astropy
 - ipykernel
 - vtk
 - matplotlib
 - mypy
 - numba
 - pandas
 - pyhdf
 - seaborn
 - pip
 - pip:
   - pyvista
   - ai.cs
   - fortranformat
   - h5py
   - ipdb
   - joblib
   - progressbar2
   - line_profiler
   - nbstripout
   - flake8
   - dask-jobqueue
   - dask
