name: dasilva-invariants
channels:
 - conda-forge
dependencies:
 - python=3
 - numpy
 - scipy
 - astropy
 - ipykernel
 - vtk
 - matplotlib
 - pandas
 - pip
 - pip:
   - pyhdf
   - pyvista
   - ai.cs
   - geopack
   - joblib
   - progressbar2
   - line_profiler
   - nbstripout