name: dasilva-invariants
channels:
 - conda-forge
dependencies:
 - python=3
 - numpy
 - scipy
 - astropy
 - ipykernel
 - vtk
 - matplotlib
 - numba
 - pandas
 - pyhdf
 - pip
 - pip:
   - pyvista
   - ai.cs
   - fortranformat
   - geopack
   - ipdb
   - joblib
   - progressbar2
   - line_profiler
   - nbstripout
   - pygeopack
