name: dasilva-invariants
channels:
 - conda-forge
dependencies:
 - python>3.8
 - pyvista
 - pip
 - pip:
    - ai.cs
    - astropy>=5.1
    - cdflib
    - flake8
    - mypy
    - numpy>=1.24
    - pandas>=1.5.2
    - PyGeopack
    - pyhdf
    - scipy>=1.9.3
    - types-python-dateutil
