name: da Silva Invariants CI
on: [push]
jobs:
  Run-Tests-and-Static-Analysis:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: dasilva-invariants
        environment-file: environment.yml
        auto-activate-base: false
    - name: Test with pytest
      run: |        
        python setup.py install
        pytest
